### ISSUE TITLE
The homepage has no effect when the plug-in is enabled

### ISSUE THREAD

**Issue by yeskpd** [hncvj/pollfish-for-wp#1]
Hello, I have opened your plug-in and completed the configuration, but the home page has no effect. Pollfish has been approved. What is the cause, or do I need to go to a specific page to activate the plug-in?

**Comment by hncvj** [comment]
Hello @yeskpd,

You need to go to Settings > Pollfish for WP

and fill in the API key and secretly received it from pollish. Your widget will show up on the website.

**Comment by hncvj** [comment]
Closed the Issue for now. You can re-open if you're still facing the same.
