### ISSUE TITLE
The plugin has been deployed, but what is the reason for the account failure?

### ISSUE THREAD

**Issue by corey-wu** [hncvj/pollfish-for-wp#2]
The plugin has been deployed, but what is the reason for the account failure?

Is it something I did wrong？

**Comment by hncvj** [comment]
> The plugin has been deployed, but what is the reason for the account failure?
> 
> Is it something I did wrong？

Where are you getting account failure?

**Comment by corey-wu** [comment]
> > The plugin has been deployed, but what is the reason for the account failure?
> > Is it something I did wrong？
> 
> Where are you getting account failure?

There is one thing I don't understand. How do I get the user ID back to pollfish? Is this plugin already passed automatically?
![image](https://user-images.githubusercontent.com/79737014/221464442-9ae6f164-89ea-4adf-a7d0-ffc0cb9df463.png)

**Comment by hncvj** [comment]
Hi @corey-wu 

It looks like they've not approved your account. Unless you have an approved account, the plugin won't work.

Regards
Vinay Jain
